#define ID_DIALOG_EXIT 0
#define ID_DIALOG_TEXT 1
#define ID_DIALOG_COMBO 2

#define ID_DIALOG_COMBO_STARTLEVEL 100
#define ID_DIALOG_COMBO_CELLDELAY 101
#define ID_DIALOG_COMBO_CELLLEVEL 102
#define ID_DIALOG_COMBO_ZERODELAY 103
#define ID_DIALOG_COMBO_ZEROTEST 104
#define ID_DIALOG_COMBO_PURGE 105
#define ID_DIALOG_COMBO_TOTALMERCURYDELAY 106
#define ID_DIALOG_COMBO_TOTALMERCURY 107
#define ID_DIALOG_COMBO_ELEMENTALMERCURYDELAY 108
#define ID_DIALOG_COMBO_ELEMENTALMERCURY 109
#define ID_DIALOG_COMBO_PRECALIBRATIONDELAY 110
#define ID_DIALOG_COMBO_CALIBRATION 111
#define ID_DIALOG_COMBO_POSTCALIBRATIONDELAY 112
